# Test GET request
GET http://localhost:8000/users
Accept: application/json

###

# Test POST request for user registration
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "username": "mod",
  "email": "mod@example.com",
  "password": "Qwerty123@",
  "role": ["moderator"]
}

###

# Test POST request for user login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "mod",
  "password": "Qwerty123@"
}