# Test GET request
GET http://localhost:8000/users
Accept: application/json

###

# Test POST request for user registration
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "username": "gene",
  "email": "gene12345@gmail.com",
  "password": "Gene123@",
  "identifier":"7"
}

###

# Test POST request for user login
POST http://localhost:8000/auth/prof-instructor-login
Content-Type: application/json

{
  "username": "yams",
  "password": "Yams123@"
}