"""deleted and init

Revision ID: 16abfb1745f9
Revises: 
Create Date: 2024-12-08 20:29:58.782648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16abfb1745f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_listed_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_jti', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_listed_tokens_hashed_jti'), 'black_listed_tokens', ['hashed_jti'], unique=True)
    op.create_index(op.f('ix_black_listed_tokens_id'), 'black_listed_tokens', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('hashed_password', sa.String(length=225), nullable=False),
    sa.Column('role', mysql.JSON(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_identifier'), 'users', ['identifier'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_identifier'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_black_listed_tokens_id'), table_name='black_listed_tokens')
    op.drop_index(op.f('ix_black_listed_tokens_hashed_jti'), table_name='black_listed_tokens')
    op.drop_table('black_listed_tokens')
    # ### end Alembic commands ###
