"""removed the default and added more user role

Revision ID: 76d87d6017b7
Revises: de7d3d115606
Create Date: 2024-12-07 21:13:09.766244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76d87d6017b7'
down_revision: Union[str, None] = 'de7d3d115606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('USER', 'ADMIN', 'MODERATOR'),
               type_=mysql.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.JSON(),
               type_=mysql.ENUM('USER', 'ADMIN', 'MODERATOR'),
               existing_nullable=False)
    # ### end Alembic commands ###
