"""added blacklistedtoken table name and jti

Revision ID: 92ef808172c4
Revises: 1b6936bafcff
Create Date: 2024-12-08 01:01:30.729894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92ef808172c4'
down_revision: Union[str, None] = '1b6936bafcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_listed_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_jti', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_listed_tokens_hashed_jti'), 'black_listed_tokens', ['hashed_jti'], unique=True)
    op.create_index(op.f('ix_black_listed_tokens_id'), 'black_listed_tokens', ['id'], unique=False)
    op.drop_index('ix_black_hashed_jti', table_name='black')
    op.drop_index('ix_black_id', table_name='black')
    op.drop_table('black')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hashed_jti', mysql.VARCHAR(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_black_id', 'black', ['id'], unique=False)
    op.create_index('ix_black_hashed_jti', 'black', ['hashed_jti'], unique=True)
    op.drop_index(op.f('ix_black_listed_tokens_id'), table_name='black_listed_tokens')
    op.drop_index(op.f('ix_black_listed_tokens_hashed_jti'), table_name='black_listed_tokens')
    op.drop_table('black_listed_tokens')
    # ### end Alembic commands ###
